# Generated by Django 5.2.4 on 2026-01-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_user', 'Can_view_user'), ('can_edit_user', 'Can_edit_user'), ('can_delete_user', 'Can_delete_user')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
