# Generated by Django 5.2.4 on 2026-01-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('checking', 'Conta corrente'), ('wallet', 'Carteira'), ('investments', 'Investimentos')], max_length=20, null=True, verbose_name='Tipo de conta'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
