# Generated by Django 5.2.4 on 2026-01-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_account_type_alter_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('checking', 'Conta corrente'), ('wallet', 'Carteira'), ('investments', 'Investimentos')], max_length=20, verbose_name='Tipo de conta'),
        ),
    ]
