# Generated by Django 5.2.4 on 2026-01-31 01:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_account_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('work', 'Trabalho'), ('investments', 'Investimentos'), ('freelance', 'Freelance'), ('home', 'Moradia'), ('food', 'Alimentação'), ('transport', 'Transporte'), ('services', 'Serviços'), ('healthy', 'Saúde'), ('leisure', 'Lazer')], max_length=30, verbose_name='Categoria')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da transação')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'db_table': 'transactions',
                'permissions': [('can_view_transaction', 'Can_view_transaction'), ('can_edit_transaction', 'Can_edit_transaction'), ('can_delete_transaction', 'Can_delete_transaction')],
            },
        ),
    ]
