# Generated by Django 5.2.4 on 2026-01-30 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('category_type', models.CharField(choices=[('income', 'Receitas'), ('expense', 'Despesas')], max_length=20, verbose_name='Tipo de Categoria')),
                ('category_color', models.CharField(choices=[('green', 'Verde'), ('darkgreen', 'Verde Escuro'), ('blue', 'Azul'), ('orange', 'Laranja'), ('brown', 'Marrom'), ('gray', 'Cinza'), ('red', 'Vermelho'), ('purple', 'Roxo')], max_length=10, verbose_name='Cor da categoria')),
                ('category_icon', models.CharField(choices=[('briefcase', 'Maleta'), ('trendingup', 'Investimentos'), ('laptop', 'Laptop'), ('home', 'Casa'), ('utensils', 'Utensílios'), ('bus', 'Ônibus'), ('wrench', 'Ferramenta'), ('heartpulse', 'Saúde'), ('partypopper', 'Lazer')], max_length=20, verbose_name='Icone da categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'category',
                'permissions': [('can_view_category', 'Can_view_category'), ('can_edit_category', 'Can_edit_category'), ('can_delete_category', 'Can_delete_category')],
            },
        ),
    ]
